#ifndef PROC_STATE_H
#define PROC_STATE_H

enum proc_state
{
	PROC_STATE_RUN,
	PROC_STATE_SLEEP,
	PROC_STATE_DISK,
	PROC_STATE_STOPPED,
	PROC_STATE_ZOMBIE,
	PROC_STATE_DEAD,
	PROC_STATE_TRACE,
	PROC_STATE_OTHER,
#define PROC_N_STATES (PROC_STATE_OTHER + 1)
} state;

#endif
