#!/usr/bin/perl

print "PID    PPID      UID GID S NI    TTY  COMMAND\n";

scalar <>;

while(<>){
	chomp;

	if(/(\d+) +(\d+) +(\d+) +(\d+) +(\S+) +(\d+) +([^\/]+) +(\/.*)/){
		my($pid, $ppid, $pgid, $winpid, $tty, $uid, $stime, $cmd) = ($1, $2, $3, $4, $5, $6, $7, $8);
		my $gid = 0;
		my $state = 'S';
		my $nice = 0;

		print "$pid $ppid $uid $gid $state $nice $tty $cmd [$winpid]\n";
	} else {
		die "invalid line $_\n";
	}
}
