.IX Title UTOP
.TH UTOP 0.9
.nh
.SH "utop"
.IX Header "utop"
utop \- process control
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
utop [\-f] [\-d] [\-t] [\-k]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
.B utop
is a simple tree-rendering process monitor.
.SH "UTOP COMMANDS"
.IX Header "UTOP COMMANDS"
.SS "Normal Modes Keys"
.IX Subsection "Normal Modes Keys"
/ - enter search
.PP
? - enter pid search
.PP
g - goto top
.PP
G - goto bottom
.PP
j, k, H, M, L, ^E, ^Y, ^U, ^D, ^F, ^B - see vi (1)
.PP
q - exit
.PP
^K - lock to process
.PP
d - kill selected process
.PP
l - lsof selected process
.PP
i - info on selected process
.PP
s - trace selected process
.PP
a - attach gdb to the selected process
.PP
r - renice selected process
.PP
o - goto locked process
.PP
O - goto $$
.PP
^L - redraw screen
.PP
Note: the "selected process" is overridden by the locked process
.SS "Search Mode Keys"
.IX Subsection "Search Mode Keys"
^K - lock to current search target
.PP
^p, ^n - next/prev search
.PP
.SH "OPTIONS"
.IX Header "OPTIONS"
\fB\-f\fR
Don't prompt for lsof, trace, etc
.PP
\fB\-d\fR
Enable debug messages on stderr
.PP
\fB\-t\fR
Thin mode - don't show as much (for small screens)
.PP
\fB\-k\fR
Show kernel threads
.PP
.SH AUTHORS
.IX Header "AUTHORS"
Rob Pilling <robpilling@gmail.com>
.PP
Florian Unglaub <f.unglaub@gmail.com>
.SH "VERSION"
.IX Header "VERSION"
Version UTOP_VERSION
.SH "NOTES"
.IX Header "NOTES"
Bugless software!
.SH "SEE ALSO"
.IX Header "SEE ALSO"
top (1), htop (1), ps (1), kvm (3), sysctl (3)
