.IX Title UTOP
.TH UTOP UTOP_VERSION
.nh
.SH "utop"
.IX Header "utop"
utop \- process control
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
utop [\-f] [\-d] [\-b] [\-k]
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
.B utop
is a simple tree-rendering process monitor.
.SH "UTOP COMMANDS"
.IX Header "UTOP COMMANDS"

.SS "Navigation Keys"
.IX Subsection "Navigation Keys"
.PP
vi (1) style navigation:
.PP
Single movement: j, k, h, l
.PP
Screen based: H, M, L
.PP
Scrolling: ^E, ^Y, ^U, ^D, ^F, ^B
.PP
Start of process names: ^
.PP
End of process names: $

.SS "Normal Modes Keys"
.IX Subsection "Normal Modes Keys"
/ - enter search
.PP
? - enter pid search
.PP
g - goto top
.PP
G - goto bottom
.PP
q - exit
.PP
f - freeze process updates
.PP
^K - lock to process
.PP
d - kill selected process
.PP
I - lsof selected process
.PP
i - info on selected process
.PP
s - trace selected process
.PP
a - attach gdb to the selected process
.PP
! - set the environment variable \fI$UTOP_PID\fR to the selected process' PID
and execute a shell
.PP
r - renice selected process
.PP
o - goto locked process
.PP
O - goto $$
.PP
^L - redraw screen
.PP
Note: the "selected process" is overridden by the locked process

.SS "Search Mode Keys"
.IX Subsection "Search Mode Keys"
^K - lock to current search target
.PP
^p, ^n - next/prev search
.PP

.SH "OPTIONS"
.IX Header "OPTIONS"
\fB\-f\fR
Don't prompt for lsof, trace, etc
.PP
\fB\-d\fR
Enable debug messages on stderr
.PP
\fB\-b\fR
Show only program basenames
.PP
\fB\-k\fR
Show kernel threads
.PP
.SH AUTHORS
.IX Header "AUTHORS"
Rob Pilling <robpilling@gmail.com>
.PP
Florian Unglaub <f.unglaub@gmail.com>
.SH "VERSION"
.IX Header "VERSION"
Version UTOP_VERSION
.SH "NOTES"
.IX Header "NOTES"
Bugless software!
.SH "SEE ALSO"
.IX Header "SEE ALSO"
top (1), htop (1), ps (1), kvm (3), sysctl (3)
